apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shreenathdiamond-tls
spec:
  secretName: shreenathdiamond
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shreenathdiamond
  dnsNames:
    - shreenathdiamond
    - www.shreenathdiamond
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shreenathdiamond
          - www.shreenathdiamond