apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shreenathdiamond-com-tls
spec:
  secretName: shreenathdiamond-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shreenathdiamond.com
  dnsNames:
    - shreenathdiamond.com
    - www.shreenathdiamond.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shreenathdiamond.com
          - www.shreenathdiamond.com